build: false
platform: x86
clone_folder: c:\projects\api-platform\core

cache:
  - '%LOCALAPPDATA%\Composer\files'

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php composer
  - refreshenv
  - cd c:\tools\php72
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo memory_limit=3G >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - composer install --no-interaction --no-progress --no-suggest

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - php vendor\behat\behat\bin\behat --format=progress --suite=default
  - php vendor\phpunit\phpunit\phpunit
