when@test:
  framework:
    test: true
api_platform:
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
  docs_formats:
    jsonopenapi: ['application/vnd.openapi+json']
  keep_legacy_inflector: false
  http_cache:
        invalidation:
            enabled: true
        public: true
  defaults:
    extra_properties:
      rfc_7807_compliant_errors: true
      standard_put: true
