when@test:
  framework:
    test: true
api_platform:
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
  event_listeners_backward_compatibility_layer: false
  keep_legacy_inflector: false
  defaults:
    extra_properties:
      rfc_7807_compliant_errors: true
      standard_put: true
